from emoji import emojize

info = emojize(":information_source:", use_aliases=True)
sopar = emojize(":hamburger:", use_aliases=True)
camera = emojize(":camera:", use_aliases=True)
date = emojize(":date:", use_aliases=True)
book = emojize(":book:", use_aliases=True)
web = emojize(":globe_with_meridians:", use_aliases=True)
lupa = emojize(":mag:", use_aliases=True)
festa = emojize(":tada:", use_aliases=True)
carpeta = emojize(":file_folder:", use_aliases=True)
creu = emojize(":x:", use_aliases=True)
ubi = emojize(":round_pushpin:", use_aliases=True)
think = emojize(":thought_balloon:", use_aliases=True)
adeu = emojize(":wave:", use_aliases=True)
dancer = emojize(":dancer:", use_aliases=True)
twitter = emojize(":loudspeaker:", use_aliases=True)
